- index.html
- package-lock.json
- package.json
- src/App.vue
- src/components/Header/index.vue
- src/components/Header/styles.css
- src/main.js
- vite.config.js
- Added [`balmUI`](https://material.balmjs.com/),
- Made header responsive,
- Styled header
> Added `header`

- package-lock.json
- package.json
- src/components/Header/index.vue
- src/components/Header/styles.css
- src/main.js
- src/modules/HashGenerator/index.mjs
- src/pages/Module/SingleGrid.css
- src/pages/Module/SingleGrid.vue
- src/pages/Module/index.vue
- src/pages/Module/styles.css
- src/stores/index.mjs
- vite.config.js
✨ Added `pinia` and removed `vuex`,
🐛 Fixed some bugs in modules logic,
✨ Added support for file input type.
> Added `pinia` and updated module logic

- package-lock.json
- package.json
- src/components/DateTimeConstants/DateTimeConstants.vue
- src/components/OutputLabel/Label.vue
- src/components/Sidebar/index.vue
- src/components/utils/TimeZoneFunctions.js
- src/components/utils/UnixDateTimeFunctions.js
- src/pages/DateToUnix/index.vue
- src/pages/DateToUnix/style.css
- src/pages/TimeZoneConverter/index.vue
- src/pages/TimeZoneConverter/style.css
- src/pages/UnixToDate/index.vue
- src/pages/UnixToDate/style.css
- src/stores/index.mjs
> add date, unix and time converter

- src/components/CopyContainer/CopyContainer.vue
- src/components/DateTimeConstants/DateTimeConstants.vue
- src/components/Sidebar/index.vue
- src/components/Sidebar/sidebarLists.js
- src/components/Sidebar/styles.css
- src/pages/DateToUnix/index.vue
- src/pages/Index/index.vue
- src/pages/Module/index.vue
- src/pages/Module/styles.css
- src/pages/TimeZoneConverter/index.vue
- src/pages/UnixToDate/index.vue
> Hari krishna 28/12 responsive UI

- package-lock.json
- package.json
- src/components/CopyContainer/MultiLineCopy.vue
- src/components/Sidebar/index.vue
- src/components/Sidebar/sidebarLists.js
- src/pages/Base64Text/index.vue
- src/pages/Base64Text/style.css
- src/pages/DateToUnix/index.vue
- src/pages/MarkdownPreview/index.vue
- src/pages/MarkdownPreview/style.css
- src/pages/Module/index.vue
- src/pages/UnixToDate/index.vue
- src/stores/index.mjs
Fixes #14 
Made it responsive for medium sized screens.
https://github.com/techrail/devta/assets/69629411/0350dfdc-b611-40cc-be02-8941562a2fde
Other changes include
> Hari krishna 28/14 UI update

- package-lock.json
- package.json
- src/components/utils/TimeZoneFunctions.js
- src/pages/DateToUnix/index.vue
- src/pages/MarkdownPreview/index.vue
- src/pages/TimeZoneConverter/index.vue
Fixes #18 
Added a check button that needs to be removed in the future.
> add timezone converter

- src/pages/JsonFormatter/index.vue
> improved json-formatter

- src/pages/TimeZoneConverter/index.vue
> Hari krishna 28/22 fix tz converter

- src/pages/JsonFormatter/index.vue
> improves UI

- package-lock.json
- package.json
- src/components/Sidebar/sidebarLists.js
- src/pages/JSONToYAML/index.vue
- src/pages/JSONToYAML/style.css
- src/pages/JsonFormatter/index.vue
- src/stores/index.mjs
> Added convert json to yaml feature and changed the copy button of json-formatter

- index.html
- package-lock.json
- package.json
- src/App.vue
- src/components/CopyContainer/MultiLineCopy.vue
- src/components/Sidebar/index.vue
- src/components/Sidebar/sidebarLists.js
- src/components/utils/JwtHelpers.js
- src/components/utils/UnixDateTimeFunctions.js
- src/components/utils/jsonBeautifier.js
- src/main.js
- src/pages/Base64Image/index.vue
- src/pages/Base64Text/index.vue
- src/pages/HashGenerator/index.vue
- src/pages/Index/index.vue
- src/pages/JWTDebugger/index.vue
- src/pages/JWTDebugger/style.css
- src/pages/Module/index.vue
- src/pages/Reflect/index.vue
- src/stores/index.mjs
Fixes #26 
Added jwt debugger and updated the sidebar logic
> Hari krishna 28/26 add jwt debugger

- package-lock.json
- package.json
- src/pages/JSONToYAML/index.vue
Removed XML option from the convert JSON
> Removed XML option

- src/pages/HashGenerator/index.vue
Refactored the UI components of hash-generator with bootstrap.
> refactor hash-generator with bootstrap

- src/components/Sidebar/index.vue
- src/pages/Index/index.vue
> fix icon relative paths

- src/pages/HashGenerator/index.vue
> update hash generator

- src/pages/Base64Text/index.vue
- src/pages/SQLFormatter/index.vue
Disabled spellcheck on SQL Formatter and enabled getting values via URL in Base64 converter
> Disabled spellcheck on SQL Formatter and enabled getting values via URL in Base64 converter

- package-lock.json
- package.json
- src/components/Sidebar/sidebarLists.js
- src/components/utils/jsonConverter.js
- src/main.js
- src/pages/JSONToYAML/index.vue
- src/pages/JSONToYAML/style.css
Fixes #60 
Added JSON to XML converter.
> Harikrishna 28/60 add xml converter

- src/pages/JSONConverter/index.vue
- src/pages/JsonFormatter/index.vue
>  Changing UI elements and adding spell-check in jsonconverter and jsonformatter

- highlight.js/styles/a11y-dark.css
- src/components/utils/MarkdownPreviewer.js
- src/stores/theme.js
Fixes #73 
screenshots of fixed issues..
> Bug fixed : Markdown style override for dark mode and dark code highlighting styles Issue #73

- src/components/Sidebar/sidebarLists.js
- src/components/utils/urlParser.js
- src/pages/URLParser/index.vue
- src/router/routes.js
Fixes #55 
Added a URL parser, that can help user to get certain information about URL.
> Added URL Parser

- src/components/Sidebar/index.vue
- src/components/Sidebar/sidebarLists.js
- src/router/routes.js
Fixes #90 
User will now be able to search for tools with tags associated with each tool.
_We'll have to modify these tags a bit._
> Modified search to search tools with tags in addition to names.

- src/components/RepFormField/index.vue
- src/components/RepFormField/style.css
- src/components/Sidebar/sidebarLists.js
- src/components/Tabs/Tab.vue
- src/components/Tabs/TabsWrapper.vue
- src/components/Tabs/index.vue
- src/components/utils/apiTester.js
- src/pages/APITester/index.vue
- src/pages/APITester/styles.css
- src/router/routes.js
A api tester feature which allows you to do basic CRUD
- supported methods GET,POST,PUT,PATCH,DELETE
- dark mode support
- responsive
> added api-tester

- src/components/Sidebar/sidebarLists.js
- src/pages/ImageToBase64/index.vue
- src/pages/ImageToBase64/style.css
- src/router/routes.js
***Created image to base64 page***
please let me know if you want any changes
> Image to base64

- src/components/CopyContainer/MultiLineCopy.vue
- src/pages/PSQLParser/index.vue
Fixes #111 
Changes done
Screenshots
> refactor using ui components

- package-lock.json
- package.json
- src/components/Sidebar/sidebarLists.js
- src/pages/CRONParser/index.vue
- src/router/routes.js
Implemented a CRON expression parser. #94
> Cron expression parser

- src/pages/MarkdownPreview/index.vue
> add markdown download

- src/pages/JsonFormatter/index.vue
- src/pages/JsonFormatter/style.css
> refactor json formatter

- src/pages/JSONConverter/index.vue
- src/pages/JSONConverter/style.css
> JSON convertor enhancements

- src/components/Sidebar/sidebarLists.js
- src/pages/ColorPickerConverter/index.vue
- src/router/routes.js
Solves issue #123 
---
**Page view**
**Grabbing an image from local drive, using eyedropper tool**
**w/ External url, using eyedropper tool**
**Color picker**
**Picking colors through the color picker**
> Color picker converter

- src/components/CopyContainer/MultiLineCopy.vue
- src/components/CopyContainer/SingleLineCopy.vue
- src/components/Sidebar/sidebarLists.js
- src/components/utils/common.js
- src/pages/LMIDGenerator/index.vue
- src/pages/LMIDGenerator/style.css
- src/router/routes.js
fixes #129 
More info on LMIDs - [Here](https://techrail.in/knowledge-base/logging-errors-properly)
Light Mode
> [Feature] Added LMID Generator

- src/components/utils/common.js
- src/pages/LMIDGenerator/index.vue
- src/pages/LMIDGenerator/style.css
Fixes #137 
Added
- shareable url
- allowed query params - `enc`, `showLogLevels`, `delta`
- bookmarkable url
Fixed
- delta input allowing letters
- error color code in dark mode
> Added Shareable LMID URL

- src/pages/ColorPickerConverter/index.vue
> add singlelinecopy component

- src/components/Sidebar/sidebarLists.js
- src/components/utils/stringCaseConverter.js
- src/pages/StringCaseConverter/index.vue
- src/pages/StringCaseConverter/style.css
- src/router/routes.js
Added a string case converter, it can convert any string into any type of case notation. (camel, snake, kebab, macro, train, pascal)
> string Case converter

- src/components/Sidebar/sidebarLists.js
- src/components/utils/backslashEscapeUnescape.js
- src/pages/BackslashEscapeUnescape/index.vue
- src/pages/BackslashEscapeUnescape/style.css
- src/router/routes.js
I added backspace escape-unescape for string, json, etc.
> Backslash Escape unescape
